[program:apache]
command=apache2-foreground
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/apache.log
stderr_logfile=/var/log/supervisor/apache.err
stopsignal=WINCH
stopwaitsecs=20
priority=10

[program:queue-worker]
command=php /var/www/html/artisan queue:work redis --queue=default --tries=1 --timeout=600 --sleep=3
user=www-data
autostart=true
autorestart=true
stopwaitsecs=620
stdout_logfile=/var/www/html/storage/logs/apartment/queue-worker.log
stderr_logfile=/var/www/html/storage/logs/apartment/queue-worker.err
priority=20

[program:scheduler]
command=php /var/www/html/artisan schedule:work
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/apartment/scheduler.log
stderr_logfile=/var/www/html/storage/logs/apartment/scheduler.err
priority=30
